### ISSUE TITLE
Support accelerator type in resource profile

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#152]
Some bespoke NVIDIA GPU device plugins do not use `nvidia.com/gpu` as the resource name.

In addition we also need to support AMD GPU images.

One potential way of expressing this:
```
resourceProfiles:
  CPU:
    requests:
      cpu: 1
      memory: "2Gi"
  EXOTICL4:
    type: NVIDIAGPU
    limits:
      nvidia.com/gpu-SOME-SILLY-SUFFIX: "1"
  L4:
    type: NVIDIAGPU
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
      cpu: "6"
      memory: "24Gi"
  MI300:
    type: AMDGPU
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
      cpu: "6"
      memory: "24Gi"
```
