### ISSUE TITLE
Adding model does not check remote model access/authorization

### ISSUE THREAD

**Issue by strus38** [substratusai/kubeai#155]
Hi,

Environment: kubeai:0.4.1

Difficult to write the right title for this one, but basically I added a model thanks to the new documentation provided last night - thank you!

```
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-3-8b
spec:
  features: ["TextGeneration"]
  owner: meta-llama
  url: hf://meta-llama/Meta-Llama-3-8B
  engine: VLLM
  minReplicas: 0
  maxReplicas: 3
  resourceProfile: CPU:4
  env:
      VLLM_CPU_KVCACHE_SPACE: "4"
  args:
  - --max-model-len=32768
  - --max-num-batched-token=32768
```
Then calling this model through the openwebui, it is stucked.
Looking at the kube logs on the pod model, I see:

```
...
huggingface_hub.utils._errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-66d1c249-75919cc37bdd839c3d8506ba;c3e0ae52-ae6f-4463-9192-5c53d581fbfc)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Meta-Llama-3-8B to ask for access.
```
Fine, some models are protected, however, how could kubeai be improved in order to know that beforehands and not discovering that through the logs?
Is it more on openwebui side, or can something be done at kubeai level to raise this when model are added?
I would also accept the 'live with it and look at licences before using the models' answer.
Thanks!
