### ISSUE TITLE
How to specify GPU type in the Model template?

### ISSUE THREAD

**Issue by strus38** [substratusai/kubeai#157]
Hi
I wanted to have a model using NVIDIA H100 GPU instead of NVIDIA T4 GPU.
In the values possible I see:

```
llama-3.1-8b-instruct-fp8-l4:
    enabled: false
    features: ["TextGeneration"]
    owner: "neuralmagic"
    url: "hf://neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8"
    engine: VLLM
    resourceProfile: L4:1
    args:
    - --max-model-len=16384
    - --max-num-batched-token=16384
    - --gpu-memory-utilization=0.9
```

Then when it is created it goes to:

```
Spec:
  Args:
    --max-model-len=16384
    --max-num-batched-token=16384
    --gpu-memory-utilization=0.9
  Engine:  VLLM
  Features:
    TextGeneration
  Max Replicas:  3
  Min Replicas:  0
  Node Selector:
    cloud.google.com/gke-accelerator:  nvidia-tesla-t4
  Owner:                               neuralmagic
  Replicas:                            1
  Resource Profile:                    L4:1
  Resources:
    Limits:
      nvidia.com/gpu:  1
    Requests:
      Cpu:             6
      Memory:          24Gi
      nvidia.com/gpu:  1
  URL:                 hf://neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
```
Editing this model with `kubectl edit model/Meta-Llama-3.1-8B-Instruct-FP8` does not keep the changes.

So how can I specify a different NodeSelector in the model definition or somewhere else?
For example:

```
Node Selector:
    cloud.google.com/gke-accelerator:  nvidia-h100-80gb
```

Thanks!

**Comment by strus38** [comment]
Oh, I just encounter #154 which maybe fit this. Am i right?

**Comment by nstogner** [comment]
You should be covered by configuring a new resource profile:

```yaml
# Example helm values file
resourceProfiles:
  H100:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
    nodeSelector:
      cloud.google.com/gke-accelerator:  nvidia-tesla-t4
```

...then configuring your Model to use it. If you are directly specifying a Model resource, just set `.spec.resourceProfile`:

```yaml
kind: Model
metadata:
  name: your-model-name
spec:
  resourceProfile: H100:1
```

If you are specifying a model via Helm:

```yaml
# helm values file example
models:
  catalog:
    your-model-name:
      enabled: true
      resourceProfile: H100:1
      # ...
```
