### ISSUE TITLE
provide way to specify minimum model replicas available

### ISSUE THREAD

**Issue by sam-huang1223** [substratusai/kubeai#247]
We should include pdbs in the helm chart to ensure the cluster autoscaler doesn't move pods around without leaving at least x active replicas.

For each model (or across all models), something like
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: model-pdb
  namespace: kubeai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      model: model-name
```
