### ISSUE TITLE
Add guide on how to expose KubeAI Server and OpenWebUI via Ingress

### ISSUE THREAD

**Issue by nstogner** [substratusai/kubeai#252]

**Comment by gentoorax** [comment]
For info I used the following values.yaml to enable ingress. By default this tries to expose kubeai server, when you probably want Open WebUI or both.

```YAML
...
ingress:
  enabled: true
  className: traefik-internal
  annotations:
    cert-manager.io/cluster-issuer: my-vault-issuer
    cert-manager.io/common-name: kubeai.internal.mydomain.net
    traefik.ingress.kubernetes.io/router.middlewares: traefik-middleware-redirect-to-https@kubernetescrd
  rules:
    - host: kubeai.internal.mydomain.net
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: kubeai-tls-secret
     hosts:
       - kubeai.internal.mydomain.net
```

**Comment by shawnho1018** [comment]
This is how I used with Gateway API to publish L7.
```
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kubeai-gw
  namespace: default
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80

---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kubeai
  namespace: default
spec:
  parentRefs:
  - name: kubeai-gw
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai/v1
    backendRefs:
    - name: kubeai
      port: 80
  - backendRefs:
    - name: openwebui
      port: 80
      ```

**Comment by dxu104** [comment]
I appreciate the shared configurations for enabling Ingress and using the Gateway API to expose KubeAI Server. I was wondering if there are any official or community tutorials that provide a guide on how to expose these services to the public using Ingress and a Load Balancer (LB).

**Comment by sjoerdvandenbos-prodrive** [comment]
```
image:
  repository: substratusai/kubeai
  pullPolicy: IfNotPresent
  tag: ""

# OpenAI API
ingress:
  enabled: true
  className: nginx
  rules:
    - host: 127.0.0.1.nip.io
      paths:
        - path: /openai/v1
          pathType: Prefix

# Open-WebUI GUI
openwebui:
  enabled: true
  ollama:
    enabled: false
  pipelines:
    enabled: false
  openaiBaseApiUrl: "http://kubeai.your-namespace.svc.cluster.local"
  ingress:
    enabled: true
    class: nginx
    host: 127.0.0.1.nip.io
    additionalHosts:
    - 127.0.0.1.nip.io
  extraEnvVars:
  - name: WEBUI_AUTH
    value: "False"
  - name: OPENAI_API_KEYS
    value: "not-used"
  - name: SHOW_ADMIN_DETAILS
    value: "false"
  - name: SAFE_MODE
    value: "true"
  - name: ENABLE_EVALUATION_ARENA_MODELS
    value: "False"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: 127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix
```

@nstogner @samos123 your open-webui subchart is defined to be a very old version.
