### ISSUE TITLE
Support for backing a single model with multiple models

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#256]
Feel free to edit this description directly.

multiple models can share the same alias.

Use cases:
* Ability to have a single model name e.g. llama-3.1-8b-instruct be backed by A100, L4, CPU.
* Ability to expose a single model as 2 names e.g. llama-3.1-8b-instruct and gpt-3.5-turbo

Add model aliases example:
```yaml
--- 
name: "llama-3.1-8b-instruct-h100"
spec:
  modelAliases: ["llama-3.1-8b-instruct"]
  minReplicas: 0
---
name: "llama-3.1-8b-instruct-a100"
spec:
  modelAliases: ["llama-3.1-8b-instruct"]
  minReplicas: 1
```
This would make both models available under the alias llama-3.1-8b-instruct. It would automatically scale up the h100 model when needed.

To discuss:
* Strategy on which model to try and scale up first
* Where to define this strategy
