### ISSUE TITLE
Support distributed inference

### ISSUE THREAD

**Issue by nstogner** [substratusai/kubeai#267]
See:
https://docs.vllm.ai/en/stable/serving/distributed_serving.html
https://github.com/kubernetes-sigs/lws/tree/main/docs/examples/vllm

**Comment by MRColorR** [comment]
I'll share here what i wrote on Discord: 

I propose a distributed VLLM engine architecture leveraging multiple nodes (n) with (m) GPUs per node.  

Kubeai will represent this resource allocation as `gpu:m:n` within model specifications expanding the use case of the alreadyexisting resource field.  

Ray will orchestrate each VLLM engine, facilitating inter-pod communication via internal cluster IPs.  

Model loading will initiate from a designated 'main' pod, one of the spawned distributed VLLM engines.  

---

The user use case involves a model distributed across m GPUs and n nodes using tensor-parallelism (m) and pipeline-parallelism (n).  
Kubeai will request the Kubernetes control plane to schedule n pods, each requiring m GPUs.  

This approach mimics kubeai current single-node setup when sufficient GPUs are available on a single node, but gracefully distributes the model across multiple nodes if a single node lacks the required m x n GPUs.

Also this is just an example and is not mandatory to link tp an pp to number of GPUs and nodes but could be beneficial in this phase to streamline the concept.

**Comment by samos123** [comment]
I think LeaderWorkerSet is the most promising solution that we could rely on. 

Example of proposal from MRColorR would be:
```
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: deepseek-r1-mi300x
spec:
  features: [TextGeneration]
  url: hf://deepseek-ai/DeepSeek-R1
  engine: VLLM
  args:
  - --tensor-parallel-size 8
  - --pipeline-parallel-size 2
  resourceProfile: nvidia-gpu-h100:8:2 # means 8 gpus per pod and needs 2 pods to run
```

KubeAI could automatically add the required additional args such as `--head`  on the head and `--address` on worker nodes or this could be a a user dependency.
