### ISSUE TITLE
Failed to aggregate stats: failed to parse metrics: text format parsing error in line 1: invalid metric name

### ISSUE THREAD

**Issue by kaiehrhardt** [substratusai/kubeai#270]
Hello, first of all, cool project. 
Unfortunately i am currently running into the following error: 
```
Failed to aggregate stats: failed to parse metrics: text format parsing error in line 1: invalid metric name . 
```
Is the error known?

versions:
```
helm-chart: 0.6.0
container-version: 0.8.0
```

model-chart:
```
catalog:
  ollama3.2-3b:
    enabled: true
    features: ["TextGeneration"]
    owner: test
    url: "ollama://llama3.2:3b"
    engine: OLlama
    resourceProfile: nvidia-gpu-test:1
```

kubeai-chart:
```
resourceProfiles:
  ...
  # self managed
  nvidia-gpu-test:
    imageName: "nvidia-gpu"
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"

modelAutoscaling:
  interval: 10s
  timeWindow: 10m
```

Thank you in advance.
