### ISSUE TITLE
feature: Support self-hosted s3 compatible storage

### ISSUE THREAD

**Issue by erhwenkuo** [substratusai/kubeai#361]
For many company, which hosted their own s3 compatible storage on premise (like Minio). It's very important to allow retrieve llm related model file from on-premise S3 storage.

In order to fulfill this feature, the system might need to allow setup three parameters for S3:
1. AWS_ACCESS_KEY_ID
2. AWS_SECRET_ACCESS_KEY
3. **AWS_ENDPOINT_URL**

The #1&#2 already cover in current KUBEAI design. I would suggest to add #3 (AWS_ENDPOINT_URL) to current design, so it will attract more enterprise to adopt KUBEAI.

**Comment by samos123** [comment]
vllm 0.6.6 now supports S3 compatible storage using RunAI model stream. That would allow setting all those parameters using environment variables: https://github.com/run-ai/runai-model-streamer/blob/master/docs/src/env-vars.md

I will test the new vLLM release and update the helm chart.

**Comment by liebman** [comment]
This almost works for me. I've:
- updated `charts/kubeai/templates/crds/kubeai.org_models.yaml` to allow s3 without cache profile
- updated `internal/modelcontroller/engine_vllm.go:vLLMPodForModel` not to change the scheme in `vllmModelFlag` if its s3 and no cache profile is specified

My issue is that no `secret` is added to the volumes of the pod, I see where the env settings are created to "optionally" add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY but nothing that adds the secret.

Ideally the secret would be specified from the Model.

Anyone have ideas or something to point me in the right direction?   

I'll put what I have so far in a PR sometime today or tomorrow. (after a bit of cleanup)

**Comment by ffais** [comment]
````@liebman this functionality is fully supported in the latest version of KubeAI.

To make it works, just add AWS credentials to the values.yaml file.

Like this:
```yaml
secrets:
  aws:
    create: true
    accessKeyID: ""
    secretAccessKey: ""
    # The name of the secret to use.
    # If not set, and create is true, the name is generated using the fullname template.
    # The secret values are pulled from the keys, "accessKeyID" and "secretAccessKey".
    name: ""

```

And if you're using an S3 storage different from AWS (minio, ceph or seaweeds), add AWS_ENDPOINT_URL to the model spec.

Like this:
```
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-test-s3
spec:
  features: [TextGeneration]
  owner: meta-llama
  url: s3://models/Meta-Llama-3.1-8B-Instruct-bnb-4bit
  engine: VLLM
  env:
    AWS_ENDPOINT_URL: http://locals3:9000
```

There's an open PR #489 to enable the support for envFrom in the models spec, useful if you need to specify different set of credentials for different models.

It might be a good idea to make using cache optional especially now that we have full support for s3-compatible storage. @samos123 what do you think?

**Comment by liebman** [comment]
I already have 
```yaml
secrets:
  aws:
    create: false
    # The name of the secret to use.
    # If not set, and create is true, the name is generated using the fullname template.
    # The secret values are pulled from the keys, "accessKeyId" and "secretAccessKey".
    name: "aws-models-il"
```
When the model pods are created the env includes 
```yaml
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: accessKeyID
          name: aws-models-il
          optional: true
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: secretAccessKey
          name: aws-models-il
          optional: true
```
but the volumes section does not reference the `aws-models-il` secret.
```yaml
  volumes:
  - emptyDir:
      medium: Memory
    name: dshm
  - name: kube-api-access-vqsn5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by liebman** [comment]
draft PR is #504

**Comment by ffais** [comment]
Since secrets.aws.create is set to false, I assume that you've already created the secrets "aws-models-il" with keys "accessKeyID" and "secretAccessKey" in the same namespace where the model is deployed. 
If the secret is present then you can also check if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are configured properly inside the container.

It is not necessary for the secret to be present in the volume list, since it is not mounted as a file but as an environment variable.

**Comment by samos123** [comment]
Thank you both! Amazing work. @liebman didn't you have to add this flag to vLLM args?
```
--load-format runai_streamer
```

I noticed in your example, you didn't set it:
```
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-test-s3
spec:
  features: [TextGeneration]
  owner: meta-llama
  url: s3://models/Meta-Llama-3.1-8B-Instruct-bnb-4bit
  engine: VLLM
  env:
    AWS_ENDPOINT_URL: http://locals3:9000
```
So was wondering whether it works without that flag.

**Comment by jez4** [comment]
I have failed in the try to make kubeai work with `--load-format runai_streamer`. The model pod was still trying to pull from hugging face even if I have configured exactly as in example. What I used is bellow:

```yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: gemma2-2b
  namespace: kubeai
spec:
  features: [TextGeneration]
  url: s3://model/gemma-2b
  engine: VLLM
  minReplicas: 1
  args:
    - --dtype=half
    - --tensor-parallel-size=1
    - --load-format=runai_streamer
  env:
     AWS_ENDPOINT_URL: http://minio-hl:9000
```
 
Instead I have managed to pull the model from minio to cache, but it consisted of adding the custom modelLoading image with hardcoded AWS_ENDPOINT_URL_S3.

Wouldn't it be possible to propagate the environment variable AWS_ENDPOINT_URL to the modelLoading image `substratusai/kubeai-model-loader`? So the `aws s3 sync` would download from minio instead of AWS S3.
