### ISSUE TITLE
How to avoid pulling the Ollama Builtin Model Docker Image repeatedly when building a Model Pod when the Image already exists on the host

### ISSUE THREAD

**Issue by leoho0722** [substratusai/kubeai#372]
Hi! I used the ollama-builtin script in the examples to pre-build the Ollama Builtin Model Docker Image and pushed it to my public Docker Hub.

When I deploy the model to the Kubernetes Cluster using the following Model kind (Kubernetes Custom Resource)

```yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: gemma2-2b
spec:
  features: [TextGeneration]
  image: leoho0722/ollama-builtin-gemma2-2b:latest
  url: ollama://gemma2:2b
  engine: OLlama
  replicas: 1
  minReplicas: 1
  maxReplicas: 10
  targetRequests: 50
  scaleDownDelaySeconds: 30
  env:
    OLLAMA_KEEP_ALIVE: "0s"
  resourceProfile: cpu:2
```

The corresponding Docker Image also exists on the host, but after executing `kubectl apply`, `kubectl describe` shows that the image is being pulled to the host.

<img width="1118" alt="Image" src="https://github.com/user-attachments/assets/07b4cdde-929c-4b39-bd44-4bf8b3177e98" />

## Environment

KubeAI version: [helm-chart-kubeai-0.11.0](https://github.com/substratusai/kubeai/releases/tag/helm-chart-kubeai-0.11.0)
Kubernetes version: Kubernetes v1.31.3 (1 Master node and 2 Worker nodes)
Operating System: Ubuntu 22.04.3 LTS
