### ISSUE TITLE
Add Support for deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B

### ISSUE THREAD

**Issue by dxu104** [substratusai/kubeai#374]
**Feature Request**  
I would like to add support for the model `deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B` in KubeAI.  

#### Changes Needed:  
1. Modify `kubeai-models.yaml` to include the new model.  
2. Update `charts/models/values.yaml` with the model configuration.  

For reference, there is an existing model config for `deepseek-r1-mi300x`:
```yaml
deepseek-r1-mi300x:
    enabled: false
    features: [TextGeneration]
    url: hf://deepseek-ai/DeepSeek-R1
    engine: VLLM
    env:
      HIP_FORCE_DEV_KERNARG: "1"
      NCCL_MIN_NCHANNELS: "112"
      TORCH_BLAS_PREFER_HIPBLASLT: "1"
      VLLM_USE_TRITON_FLASH_ATTN: "0"
      VLLM_FP8_PADDING: "0"
    args:
      - --trust-remote-code
      - --max-model-len=32768
      - --max-num-batched-token=32768
      - --max-num-seqs=1024
      - --num-scheduler-steps=10
      - --tensor-parallel-size=8
      - --gpu-memory-utilization=0.90
      - --disable-log-requests
      - --enable-chunked-prefill=false
      - --max-seq-len-to-capture=16384
      - --kv-cache-dtype=fp8
    resourceProfile: amd-gpu-mi300x:8
    targetRequests: 1024
```

#### Questions:  
- Should `deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B` use similar `env:` and `args:` settings as `deepseek-r1-mi300x`?  
- How do we determine the correct parameters for this model?  
- Are there any other config files that need to be updated to support this model?  

Hugging Face model link: [https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B](https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B)  

Thanks!
