### ISSUE TITLE
Add observability docs on how to get vLLM metrics, setup Prometheus and Grafana

### ISSUE THREAD

**Issue by Ashley-Tung** [substratusai/kubeai#391]
Hello, I am following the tutorial on installing [KubeAI on any Kubernetes cluster](https://www.kubeai.org/installation/any/) and I am able to successfully communicate with a vllm models [following this tutorial](https://www.kubeai.org/how-to/configure-text-generation-models/).
```
root@yuegpu:~# curl "http://localhost:8000/openai/v1/chat/completions" \
    -H "Content-Type: application/json" \
    -d '{
        "model": "gemma2-2b-cpu",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Write a haiku about recursion in programming."
            }
        ]
    }'
{"id":"chatcmpl-599","object":"chat.completion","created":1739212181,"model":"gemma2-2b-cpu","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"Code unwinds itself,\nA mirror's reflections form,\nBack to its own base. \n"},"finish_reason":"stop"}],"usage":{"prompt_tokens":28,"completion_tokens":23,"total_tokens":51}}
```

Now, my next step is to grab metrics data from the vllm model. I have done this before when running just vllm on my host [following this tutorial](https://docs.vllm.ai/en/stable/serving/metrics.html). However, with this KubeAI setup, it's not as simple as running the curl command anymore.
```
root@yuegpu:~# curl http://0.0.0.0:8000/metrics
404 page not found
```

Is there documentation on how I am able to use vllm's metrics when it exists in my kubernetes pod? Any help would be appreciated.

**Comment by samos123** [comment]
Does this help? https://github.com/substratusai/kubeai/issues/299#issuecomment-2458787717

Note I plan to work on adding built-in prometheus + grafana examples that can be enabled.

**Comment by Ashley-Tung** [comment]
So with this metric scraping pod
```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllm-pods
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  endpoints:
  - port: http
    interval: 30s
```

What this will do is select pods with the label matching `app.kubernetes.io/name: vllm` and scrape metrics from it? Since this is already, as you say, a "Google managed Prometheus," will I be able to use its endpoint as a datasource for my Grafana dashboard?

**Comment by Ashley-Tung** [comment]
Hi @samos123 , thanks for your input. Following your yaml file, the pods are up and running for prometheus
```
(myenv) [ec2-user@ip-kubectl get pods -A | grep prometheus
monitoring           alertmanager-prometheus-operator-kube-p-alertmanager-0   2/2     Running   0          12m
monitoring           prometheus-operator-grafana-5688cb87bc-7d7cq             3/3     Running   0          12m
monitoring           prometheus-operator-kube-p-operator-5c67fdfb57-g42sc     1/1     Running   0          12m
monitoring           prometheus-operator-kube-state-metrics-57588f85-vkg89    1/1     Running   0          12m
monitoring           prometheus-operator-prometheus-node-exporter-tgflc       1/1     Running   0          12m
monitoring           prometheus-prometheus-operator-kube-p-prometheus-0       2/2     Running   0          12m
```
Afterwards, I did forward the port following the below instructions so that I may access Grafana on my browser
```
export POD_NAME=$(kubectl --namespace monitoring get pod -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=prometheus-operator" -oname)
  kubectl --namespace monitoring port-forward $POD_NAME 3000
```

However, it seems unable to connect. I am running on an AWS instance and 3000 is open in my security group. From here, how can I access Grafana?

**Comment by samos123** [comment]
Grafana with Prometheus using the helm kube-prometheus-stack chart was working fine for me.

![Image](https://github.com/user-attachments/assets/62697843-81c4-4366-ac45-8d6cfad52c91)

I will add an end to end tutorial soon. I did notice I had to delete the prometheus operator and prometheus pod after adding the PodMonitor. It wouldn't pick it up automatically otherwise.

This was the PodMonitor that worked for me:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-pods
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
  - port: http
```

Installed Prometheus and Grafana like this:
```
helm install prometheus prometheus-community/kube-prometheus-stack
```

**Comment by samos123** [comment]
This should work end-to-end without having to restart:
```
cat > values-prometheus.yaml <<EOF
additionalPodMonitors:
  - name: vllm
    selector:
      matchLabels:
        app.kubernetes.io/name: vllm
    podMetricsEndpoints:
      - port: http
EOF

helm install prometheus prometheus-community/kube-prometheus-stack -f values-prometheus.yaml
```

At least for me it did. Please give it a try and report back @Ashley-Tung

**Comment by samos123** [comment]
@Ashley-Tung please see this PR with more details: https://github.com/substratusai/kubeai/pull/396

**Comment by Ashley-Tung** [comment]
Hi @samos123 , thanks for the response! I had a different prometheus installation with `helm install prometheus-operator prometheus-community/kube-prometheus-stack`. I uninstalled it and tried your installation command and using your yaml file (followed the instructions on the PR #396 as well).

Unfortunately, I still do not see any vllm metrics on my end.
![Image](https://github.com/user-attachments/assets/012ceccd-7267-46e9-b247-30d50fe28754)
If I were to port forward 8000, I am able to curl the initial vllm metrics so they do exist for the vllm model. This picture also shows my pods.
![Image](https://github.com/user-attachments/assets/f8baf770-4e36-4bf5-80fd-3231929c7ca0)

**Comment by samos123** [comment]
Send some requests might help and it should show data. I can see in your screenshot that data is being populated because some of the graphs have data.

**Comment by Ashley-Tung** [comment]
Currently I am using the `facebook/opt-125m` model on CPU. The curl command I usually use looks like
```
curl "http://localhost:8000/openai/v1/chat/completions" \
    -H "Content-Type: application/json" \
    -d '{
        "model": "opt-125m-cpu",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Write a haiku about recursion in programming."
            }
        ]
    }'
```
However, the logs are saying this is an outdated template - which coincides with the "Bad Request" error I am getting
![Image](https://github.com/user-attachments/assets/f0f0f6dc-cb6d-4b58-8f11-32e60a1d5e35)

**Comment by samos123** [comment]
I see. Looks like that model is no longer valid in latest vLLM. Can you try using the completion API endpoint? Like this:

```
  curl http://localhost:8000/openai/v1/completions \
    --max-time 600 \
    -H "Content-Type: application/json" \
    -d '{"model": "opt-125m-cpu", "prompt": "Who was the first president of the United States?", "max_tokens": 40}'
```

completion api should still work.

**Comment by Ashley-Tung** [comment]
Restarting the prometheus pods with
```
helm upgrade prometheus prometheus-community/kube-prometheus-stack -f - <<EOF
additionalPodMonitors:
  - name: vllm
    selector:
      matchLabels:
        app.kubernetes.io/name: vllm
    podMetricsEndpoints:
      - port: http
EOF
```

Unfortunately I have the same issue of no vllm metrics or model found for the vllm dashboard
![Image](https://github.com/user-attachments/assets/d86ee8c5-9cc5-4517-9b4a-8d123f20737a)

I am able to curl the metrics locally at least after I forward the port via `kubectl port-forward --address 0.0.0.0 pomodel-deepseek-qwen-1.5b-cpu-58d66788cf-99w6z  9000:8000`
![Image](https://github.com/user-attachments/assets/545b0b88-a213-45cb-94a7-737875f0aa80)

**Comment by samos123** [comment]
What about using Metrics Explorer? Do the metrics show up there?

**Comment by Ashley-Tung** [comment]
Unfortunately, no vllm metrics found in the metrics explorer
![Image](https://github.com/user-attachments/assets/1a84c28c-2c80-442b-8197-2464a0ba2eba)

Checking the logs of all the `prometheus` pods I have, unfortunately no `/metrics` endpoint is found.
```
ubuntu@ip-172-31-45-135:~$ kubectl logs prometheus-kube-prometheus-operator-94cc5845d-th69r | grep metrics

ubuntu@ip-172-31-45-135:~$ kubectl logs prometheus-grafana-856fbd5d8c-jjrsl | grep metrics
logger=resource-server t=2025-02-12T22:44:10.34357857Z level=warn msg="failed to register storage metrics" error="duplicate metrics collector registration attempted"
logger=resource-server t=2025-02-12T22:44:10.343646947Z level=warn msg="failed to register storage metrics" error="duplicate metrics collector registration attempted"
logger=resource-server t=2025-02-12T22:44:10.34368152Z level=warn msg="failed to register storage metrics" error="duplicate metrics collector registration attempted"

ubuntu@ip-172-31-45-135:~$ kubectl logs prometheus-kube-state-metrics-ff54496d6-xvh7w  | grep metrics
I0212 22:43:59.385276       1 wrapper.go:120] "Starting kube-state-metrics"
I0212 22:43:59.392924       1 server.go:361] "Started metrics server" metricsServerAddress="[::]:8080"
I0212 22:43:59.392964       1 metrics_handler.go:110] "Autosharding disabled"
I0212 22:43:59.392971       1 server.go:350] "Started kube-state-metrics self metrics server" telemetryAddress="[::]:8081"

ubuntu@ip-172-31-45-135:~$ kubectl logs prometheus-prometheus-kube-prometheus-prometheus-0  | grep metrics
time=2025-02-12T22:44:10.562Z level=INFO source=kubernetes.go:327 msg="Using pod service account via in-cluster config" component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/default/prometheus-kube-state-metrics/0

ubuntu@ip-172-31-45-135:~$ kubectl logs prometheus-prometheus-node-exporter-gzw9h | grep metrics
```

**Comment by Ashley-Tung** [comment]
I tried submitting the model the same way as before, with specifying `kind: Model`, but it seems it did not work either. I have the model yaml file as 
```
# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
 name: deepseek-r1-distill-llama-8b-l4
spec:
 features: [TextGeneration]
 url: hf://deepseek-ai/DeepSeek-R1-Distill-Llama-8B
 engine: VLLM
 args:
  - --max-model-len=8192
  - --max-num-batched-token=8192
  - --max-num-seqs=256
  - --gpu-memory-utilization=0.95
  - --kv-cache-dtype=fp8
  - --disable-log-requests
  - --quantization=fp8
  - --enforce-eager
 env:
  VLLM_ATTENTION_BACKEND: FLASHINFER
 resourceProfile: nvidia-gpu-l4:1
```

but bringing up the prometheus pods the same way does not allow it to see the model
![Image](https://github.com/user-attachments/assets/1fbd6e95-302a-4935-8806-164f1d6f0d88)

**Comment by samos123** [comment]
Can you check if the model pod logs are getting hits `/metrics` endpoint? Also please run `kubectl describe podmonitor`.

**Comment by Ashley-Tung** [comment]
Sure, here is the contents of `kubectl describe podmonitor`. There is nothing here. Is that expected? My yaml file is the same as your
```
ubuntu@ip-172-31-45-135:~$ kubectl describe podmonitor
No resources found in default namespace.

ubuntu@ip-172-31-45-135:~$ cat values-prometheus.yaml
additionalPodMonitors:
  - name: vllm
    selector:
      matchLabels:
        app.kubernetes.io/name: vllm
    podMetricsEndpoints:
      - port: http
```

As for the model's pod logs themselves, I did check that they had the right label `app.kubernetes.io/name=vllm`. I do see a `metrics.py` file in the pod logs but nothing about an endpoint
```
ubuntu@ip-172-31-45-135:~$ kubectl logs  model-deepseek-qwen-1.5b-cpu-58d66788cf-99w6z | grep metric
INFO 02-12 22:52:43 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 02-12 22:52:53 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
...
```

**Comment by samos123** [comment]
Can you try defining the podmonitor manually? like this:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-pods
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
  - port: http
```

**Comment by Ashley-Tung** [comment]
Updated my  `values-prometheus.yaml` file and restarted the pod with `helm upgade prometheus prometheus-community/kube-prometheus-stack -f values-prometheus.yaml` but unfortunately I still cannot see vllm metrics.
![Image](https://github.com/user-attachments/assets/be86a4af-0357-4106-9b92-0e6b6f2c6977)

**Comment by Ashley-Tung** [comment]
No contents under ` kubectl describe podmonitor` either

**Comment by Ashley-Tung** [comment]
Another interesting behavior I have replicated over and over again is if the PodMonitor yaml file remains unchanged between uninstallations and installations, I do not see my models in Prometheus.

However, if I update the PodMonitor in between uninstallations and installations, I can see the models. [Here is a quick video recording it](https://youtu.be/NddJCHKnKAA). It seems it is not consistent with either yaml file. The two yaml files are
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-pods
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
  - port: http

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-pods
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
    - port: http  
      path: /metrics 
```
