### ISSUE TITLE
How to specify GPU type in KubeAI when using AWS GPU Pool

### ISSUE THREAD

**Issue by dxu104** [substratusai/kubeai#393]
#### Description  
I followed the [[EKS installation guide](https://www.kubeai.org/installation/eks/)](https://www.kubeai.org/installation/eks/) for KubeAI and created a GPU node pool using Karpenter. I then attempted to install a text-generation model as per [[this guide](https://www.kubeai.org/how-to/configure-text-generation-models/)](https://www.kubeai.org/how-to/configure-text-generation-models/) using the following `helm upgrade` command:  

```sh
helm upgrade --install --reuse-values kubeai-models kubeai/models -f - <<EOF
catalog:
  llama-3.1-8b-instruct-fp8-l4:
    enabled: true
    engine: VLLM
    resourceProfile: nvidia-gpu-l4:1
    minReplicas: 1
EOF
```

However, I am unsure if my AWS GPU node pool is actually provisioning G-series GPUs that include L4 GPUs. The current Karpenter configuration for node provisioning is as follows:  

```yaml
template:
  spec:
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["g"]
```

Since AWS G-series instances include multiple GPU types:  

- **G4dn** – NVIDIA T4 Tensor Core GPU  
- **G4ad** – AMD Radeon Pro V520 GPU  
- **G5** – NVIDIA A10G Tensor Core GPU  
- **G5g** – NVIDIA T4G Tensor Core GPU  
- **G6** – NVIDIA L4 Tensor Core GPU  
- **G6e** – NVIDIA L40S Tensor Core GPU  

There is a possibility that AWS might provision a **G4dn** instance (T4 GPU) instead of a **G6** instance (L4 GPU). Since my `resourceProfile` is set to `nvidia-gpu-l4:1`, would this result in a scheduling failure or other errors if a non-L4 GPU (e.g., T4 from G4dn) is provisioned?  

#### Proposed Solution  
One potential fix is explicitly setting:  

```yaml
values: ["g6.xlarge"]
```

This ensures that AWS only provisions G6 instances, which use L4 GPUs. However, this approach is restrictive—if I later deploy a larger model that requires a different GPU, the scheduling might fail due to resource constraints.  

Would it be possible to modify:  

```yaml
resourceProfile: nvidia-gpu-l4:1
```

to something more flexible, like:  

```yaml
resourceProfile: gpu-pool
```

This would allow the model deployment to work with multiple GPU types without explicitly limiting the node instance type.  

Would appreciate any insights on best practices for handling this scenario.  

Thank you!

**Comment by samos123** [comment]
Yeah you can define a resourceProfile with no nodeSelectors like this:
```
  nvidia-gpu-any:
    imageName: "nvidia-gpu"
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
```

That would achieve what you want.

**Comment by dxu104** [comment]
@samos123 @nstogner Thank you so much for your help. Below are details of the suggested solution:



**Suggested Solution:**  
To make GPU scheduling more flexible, I updated the `resourceProfiles` configuration file `values-eks.yaml ` to include a more general GPU profile:  

```yaml
resourceProfiles:
  nvidia-gpu-l4:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "l4"
  nvidia-gpu-l40s:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "l40s"
  nvidia-gpu-h100:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "h100"
  nvidia-gpu-a100-80gb:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "a100"
      karpenter.k8s.aws/instance-gpu-memory: "81920"
  nvidia-gpu-a100-40gb:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "a100"
      karpenter.k8s.aws/instance-gpu-memory: "40960"
  nvidia-gpu-any:
    imageName: "nvidia-gpu"
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
```

With this change, I also updated the `helm upgrade` command to use the more flexible `nvidia-gpu-any` profile:  

```sh
helm upgrade --install --reuse-values kubeai-models kubeai/models -f - <<EOF
catalog:
  llama-3.1-8b-instruct-fp8-l4:
    enabled: true
    engine: VLLM
    resourceProfile: nvidia-gpu-any
    minReplicas: 1
EOF
```

This allows the model deployment to work with multiple GPU types instead of being restricted to L4 GPUs.
