### ISSUE TITLE
kubeai does not use VLLM metrics to do autoscale (Solved)

### ISSUE THREAD

**Issue by dxu104** [substratusai/kubeai#405]
### **Context**  
I am following the [[[autoscaling configuration guide](https://github.com/substratusai/kubeai/blob/main/docs/how-to/configure-autoscaling.md)](https://github.com/substratusai/kubeai/blob/main/docs/how-to/configure-autoscaling.md)](https://github.com/substratusai/kubeai/blob/main/docs/how-to/configure-autoscaling.md) and have set up my model with the following configuration:

```bash
helm upgrade kubeai-models kubeai/models -f - <<EOF
catalog:
  llama-3.1-8b-instruct-fp8-l4:
    enabled: true
    cacheProfile: efs-dynamic
    minReplicas: 1
    maxReplicas: 2
    targetRequests: 1
    scaleDownDelaySeconds: 45
  deepseek-r1-distill-llama-8b-l4:
    enabled: true
    cacheProfile: efs-dynamic
    minReplicas: 1
    maxReplicas: 2
    targetRequests: 1
    scaleDownDelaySeconds: 45
EOF
```

I can successfully send queries from the WebUI. Now, I am testing autoscaling using a simple script, running it concurrently in three terminals:  

```bash
#!/bin/bash

# Target model endpoint
MODEL_URL="http://localhost:8000/v1/chat/completions"

# Function to send a request and wait for a response
send_request() {
    response_code=$(curl -X POST "$MODEL_URL" \
         -H "Content-Type: application/json" \
         --data '{
            "model": "deepseek-r1-distill-llama-8b-l4",
            "messages": [
                {"role": "user", "content": "What is the capital of France?"}
            ],
            "max_tokens": 100
         }' -s -o /dev/null -w "%{http_code}")

    echo "Response Code: $response_code"

    if [[ "$response_code" == "200" ]]; then
        return 0  
    else
        echo "🚨 Received a non-200 response: $response_code. Retrying..."
        return 1  
    fi
}

# Step 1: Check the initial Pod count
echo "🔍 Checking initial Pod count..."
kubectl get pods -l model=deepseek-r1-distill-llama-8b-l4

# Step 2: Continuous request loop (infinite loop)
echo "🚀 Sending continuous queries... Press Ctrl+C to stop."
while true; do
    send_request
done

# This part will never be reached unless the script is manually stopped
echo "✅ Load test completed!"
```

---

### **Questions**  

1. The documentation mentions the following autoscaling configuration in `helm-values.yaml`:  
   ```yaml
   modelAutoscaling:
     interval: 15s
     timeWindow: 10m
   ```
   Can users modify these parameters? If so, how?  

2. My autoscaling settings are:  
   ```yaml
   minReplicas: 1
   maxReplicas: 2
   targetRequests: 1
   ```
   I expected autoscaling to work, but it is not triggering as expected. I confirmed that I have sufficient GPU quota. Is there anything I might be missing?  

Would appreciate any insights. Thanks!

**Comment by samos123** [comment]
1. You don't have to tweak `modelAutoscaling`. You can specify `modelAutoscaling` config in the helm values file. See here for reference: https://github.com/substratusai/kubeai/blob/main/charts/kubeai/values.yaml#L196
2. There should definitely be 2 pods created if you have more than 2 concurrent requests. Can you show the kubeai pod logs as well? You can also take a look at our e2e tests that verifies autoscaling works on every PR: https://github.com/substratusai/kubeai/blob/main/test/e2e/autoscaler-restart-under-load/test.sh#L17

**Comment by dxu104** [comment]
@samos123 
I expected that with targetRequests: 1, sending just a single query should trigger autoscaling immediately.

Curently I am running it concurrently in three terminals.

Below are pod logs:


Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%.
INFO:     127.0.0.1:35886 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:35896 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:35904 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 02-13 12:01:15 metrics.py:453] Avg prompt throughput: 7.1 tokens/s, Avg generation throughput: 70.5 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%.
INFO:     127.0.0.1:35914 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:34942 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.173.11:58992 - "GET /health HTTP/1.1" 200 OK
INFO:     192.168.173.11:59008 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:34946 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:34954 - "POST /v1/chat/completions HTTP/1.1" 200 OK

**Comment by dxu104** [comment]
When I open **five OpenWebUI tabs** in the browser and send concurrent queries, autoscaling **successfully scales up** as expected.  

However, when using the following method, **autoscaling does not trigger** despite continuously sending requests.

### **Steps to Reproduce**  

#### **1. Deploy Model Service**  

I have deployed a model service (`deepseek-r1-distill-llama-8b-l4`) with the following Helm configuration:

```yaml
catalog:
  deepseek-r1-distill-llama-8b-l4:
    enabled: true
    cacheProfile: efs-dynamic
    minReplicas: 1
    maxReplicas: 3
    targetRequests: 1
    scaleDownDelaySeconds: 45
    modelAutoscaling:
      interval: 2s
      timeWindow: 10s
```

#### **2. Wrap the Model in a LoadBalancer Service**  

```yaml
apiVersion: v1
kind: Service
metadata:
  name: deepseek-r1-distill-llama-8b-l4
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    model: deepseek-r1-distill-llama-8b-l4
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
```

#### **3. Port-forward the Service**  

```bash
kubectl port-forward svc/deepseek-r1-distill-llama-8b-l4 8000:8000
```
This exposes port **8000** locally.

---

### **Issue: Autoscaling Doesn't Trigger via Script**

When I run the following **Bash script** on the **Kubernetes head node** to continuously send requests, it does **not** trigger autoscaling:


### **Observations**
- Queries from **OpenWebUI (5 concurrent browser tabs)** successfully trigger autoscaling.  (`kubectl port-forward --address 0.0.0.0 svc/openwebui`)
- Queries from **the script running on the Kubernetes head node** **do not** trigger autoscaling, even though the requests return HTTP 200.  (via `kubectl port-forward svc/deepseek-r1-distill-llama-8b-l4`)
