### ISSUE TITLE
PersistentVolumeClaim Binding Issue with Updated Service Name (open-webui)

### ISSUE THREAD

**Issue by dxu104** [substratusai/kubeai#420]
**Description:**

I encountered an issue while installing KubeAI using Helm. The service name seems to have changed from `openwebui` to `open-webui`. This causes the following error during installation:

```
ready.go:284: PersistentVolumeClaim is not bound: default/open-webui
```

**Steps to Reproduce:**

 Run the installation command as mentioned in the documentation (https://www.kubeai.org/installation/eks/):

   ```bash
   helm upgrade --install kubeai kubeai/kubeai \
     -f values-eks.yaml \
     --set secrets.huggingface.token=$HF_TOKEN \
     --wait --debug
   ```

Has anyone faced a similar issue before? Any help would be greatly appreciated! 🙏

**Comment by samos123** [comment]
I think the issue is that you don't have a default storageclass defined

can you run kubectl get storageclass?

You may have to override the Open Web UI storageclass like this: https://github.com/open-webui/helm-charts/blob/6ba37844ec9af347d46d37b405aa01fbe62bb357/charts/open-webui/values.yaml#L206

**Comment by dxu104** [comment]
```
 kubectl get storageclass
NAME   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2    kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  11d
```

Thank you for your help. Does this look correct?

**Comment by dxu104** [comment]
> Before the update to the `open-webui` service, everything was working fine. I also followed your tutorial to install EFS successfully.  
> 
> However, after the recent update, when I run:
> ```bash
> helm upgrade kubeai-models
> ```
> the `open-webui` pod stays stuck in a **Pending** state.  
> 
> Here is the error message I get:
> ```
> Events:
>   Type     Reason            Age                     From               Message
>   ----     ------            ----                    ----               -------
>   Warning  FailedScheduling  16m (x1025 over 4d20h)  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
>   Warning  FailedScheduling  10s (x366 over 3d23h)   default-scheduler  0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
> ```
>

**Comment by dxu104** [comment]
Thanks for the help. I changed the storageClass from `"gp2"` to `"efs-sc"` in my values-eks.yaml and everything works fine. (Note: To use efs-sc, you must follow the "Cache models with AWS EFS" tutorial; otherwise, you need to set `enabled: false`.)

My updated configuration is:

```yaml
open-webui:
  persistence:
    enabled: true
    size: 2Gi
    # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
    existingClaim: ""
    # -- Subdirectory of Open WebUI PVC to mount. Useful if root directory is not empty.
    subPath: ""
    # -- If using multiple replicas, you must update accessModes to ReadWriteMany
    accessModes:
      - ReadWriteOnce
    storageClass: "efs-sc"
    selector: {}
    annotations: {}
```

I added the above content into my values-eks.yaml and then ran:

```bash
helm upgrade --install kubeai kubeai/kubeai -f values-eks.yaml --set secrets.huggingface.token=$HF_TOKEN --wait --timeout 15m --debug
```

After this, everything worked fine. Thanks again for your assistance!
