### ISSUE TITLE
How to Deploy DeepSeek R1 617B via KubeAI on AWS EKS with H100 GPU Nodes

### ISSUE THREAD

**Issue by dxu104** [substratusai/kubeai#421]
**Description:**  

We have successfully deployed the following models using **KubeAI** on our **AWS EKS cluster**:  
- `llama-3.1-8b-instruct-fp8-l4`  
- `deepseek-r1-distill-llama-8b-l4`  

However, when attempting to deploy the **DeepSeek R1 617B** model (defined in `DeepSeek-R1.yaml`), we encountered scheduling issues. The details are as follows:

---

### **1. AWS Quota and Instance Type Availability:**

- Using the following command, we confirmed that our **Running On-Demand P instances** quota is set to **800 vCPUs**:

  ```bash
  aws service-quotas list-service-quotas --service-code ec2 --region us-west-2 --query "Quotas[?contains(QuotaName, 'P instance')]"
  ```

  Output:

  ```json
  {
      "QuotaName": "Running On-Demand P instances",
      "Value": 800.0,
      ...
  }
  ```

- We also verified available instance types with:

  ```bash
  aws ec2 describe-instance-type-offerings --location-type availability-zone --filters Name=instance-gpu-name,Values=h100 --region us-west-2
  ```

---

### **2. Karpenter NodePool and EC2NodeClass Configuration:**

We are using the following **NodePool** configuration for GPU nodes:

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["g", "p"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu
      expireAfter: 720h
      taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```

And the corresponding **EC2NodeClass** configuration:

```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiFamily: AL2
  role: "eksctl-KarpenterNodeRole-${CLUSTER_NAME}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  amiSelectorTerms:
    - id: "${GPU_AMI_ID}"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true
```

---

### **3. Model Deployment Configuration (DeepSeek-R1.yaml):**

The deployment file for **DeepSeek R1 617B** specifies the following configuration:

```yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: deepseek-617b-h100
spec:
  features: [TextGeneration]            # Adjust according to model capability
  url: hf://deepseek-ai/DeepSeek-R1     # Replace with actual Hugging Face path for DeepSeek 617B
  engine: VLLM                          # If using DeepSpeed instead of VLLM, update accordingly
  args:
    - --max-model-len=65536             # Max sequence length
    - --max-num-batched-token=65536     # Max batched tokens
    - --gpu-memory-utilization=0.9      # GPU memory utilization setting
    - --tensor-parallel-size=8          # Using 8 GPUs as required
    - --enable-prefix-caching           # Enable prefix caching
    - --disable-log-requests            # Disable request logging (optional)
    - --max-num-seqs=1024               # Max sequences per batch
    - --kv-cache-dtype=fp8              # Data type for KV cache
  targetRequests: 500                   # Adjust according to expected load
  resourceProfile: nvidia-gpu-h100:8    # Specify H100 GPU nodes with 8 GPUs
```

In `values-eks.yaml`, the resource profile is defined as:

```yaml
resourceProfiles:
  nvidia-gpu-h100:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-name: "h100"
```

---

### **4. Scheduling Errors:**

We are encountering the following errors during pod scheduling:

```
Warning  FailedScheduling  38s (x13 over 60m)  default-scheduler  0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

```
  Warning  FailedScheduling  7m57s (x2 over 12m)   karpenter          Failed to schedule pod, incompatible with nodepool "gpu", daemonset overhead={"cpu":"150m","pods":"5"}, no instance type satisfied resources {"cpu":"150m","nvidia.com/gpu":"8","pods":"6"} and requirements karpenter.k8s.aws/instance-category In [g p], karpenter.k8s.aws/instance-gpu-name In [h100], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [gpu] (no instance type met all requirements)
  Warning  FailedScheduling  3m14s (x18 over 88m)  default-scheduler  0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

---

### **Expected Behavior:**

Any instance type that satisfies the following conditions should be provisioned:
- Supports at least **8 H100 GPUs**.
- Meets the resource requests for CPU and memory as specified in the deployment configuration.
- Falls within the **On-Demand P instance** quota of **800 vCPUs**.

---

### **Actual Behavior:**

Despite the correct quota and available GPU instance types, our pods are not being scheduled. The scheduler reports issues related to resource constraints and node affinity mismatches.

---

### **Questions:**

- Why aren’t instances (with H100 GPUs) being launched, even though our AWS quotas are correctly set and available instances meet the required specifications?  
- Are there additional configurations needed for Karpenter to correctly provision nodes with H100 GPUs?  

Any guidance or insights to help resolve this issue would be greatly appreciated. Thank you for your help!

**Comment by samos123** [comment]
I think you need to modify Karpenter config because this is seen in your logs:
 Warning  FailedScheduling  7m57s (x2 over 12m)   karpenter          Failed to schedule pod, incompatible with nodepool "gpu", daemonset overhead={"cpu":"150m","pods":"5"}, no instance type satisfied resources {"cpu":"150m","nvidia.com/gpu":"8","pods":"6"} and requirements karpenter.k8s.aws/instance-category In [g p], karpenter.k8s.aws/instance-gpu-name In [h100], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [gpu] (no instance type met all requirements)

I don't know much about AWS so that's as much as I can help.

Note that Deepseek R1 671b will not fit on 8 x H100 not even with fp8. You would have to run it in 4 bit. I'm mentioning this since even if you get H100 working, you still would hit GPU OOM issues.

**Comment by dxu104** [comment]
Thank you so much for help!


I followed this [[GitHub link](https://github.com/substratusai/kubeai/blob/60e295bb5a9a21ec370b16e6c5effd4b7b7bbf86/manifests/models/llama-3.1-405b-instruct-fp8-h100.yaml#L4)](https://github.com/substratusai/kubeai/blob/60e295bb5a9a21ec370b16e6c5effd4b7b7bbf86/manifests/models/llama-3.1-405b-instruct-fp8-h100.yaml#L4) and used the following configuration:

```yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-3.1-405b-instruct-fp8-h100
spec:
  features: [TextGeneration]
  url: hf://neuralmagic/Meta-Llama-3.1-405B-Instruct-FP8
  engine: VLLM
  args:
    - --max-model-len=65536
    - --max-num-batched-token=65536
    - --gpu-memory-utilization=0.9
    - --tensor-parallel-size=8
    - --enable-prefix-caching
    - --disable-log-requests
    - --max-num-seqs=1024
    - --kv-cache-dtype=fp8
  targetRequests: 500
  resourceProfile: nvidia-gpu-h100:8
```

However, I got the following scheduling errors:

```
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m47s  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling  2m46s  karpenter          Failed to schedule pod, incompatible with nodepool "gpu", daemonset overhead={"cpu":"150m","pods":"5"}, no instance type satisfied resources {"cpu":"150m","nvidia.com/gpu":"8","pods":"6"} and requirements karpenter.k8s.aws/instance-category In [g p], karpenter.k8s.aws/instance-gpu-name In [h100], karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [gpu] (no instance type met all requirements)
  Normal   Nominated         19s    karpenter          Pod should schedule on: nodeclaim/gpu-rjbdn
```

**Possible Issue:**
I think AWS might not have enough available **H100 GPU instances** in the region I'm using, which is causing the pod scheduling to fail. I  maybe try to request Spot Instances from AWS.
