### ISSUE TITLE
Consistent Hashing Routing Issue

### ISSUE THREAD

**Issue by liaddrori1** [substratusai/kubeai#447]
### Description
We've identified a strange issue with routing in KubeAI. The cause is unclear, but here are the details:

KubeAI was running for a few days when we encountered this issue. We had one model configured with a minimum of 10 replicas.

### Load Balancing Configuration
```yaml
Load Balancing:
  Prefix Hash:
    Mean Load Factor:      125
    Prefix Char Length:    100
    Replication:           20
```
###  Observed Behavior

- The majority of requests were routed to a single pod, despite having different prefixes.
- This issue occurred multiple times across different VLLM pods.
- KubeAI seemed to favor one specific pod, directing most traffic there.
- One pod received around 80 requests, while others only received between 1 and 10.

![Image](https://github.com/user-attachments/assets/c0359b02-5b3e-4ae8-a709-cbfd044f9ccc)

After restarting KubeAI, routing became more balanced.

![Image](https://github.com/user-attachments/assets/91dd617a-1749-40a1-a1bc-2573604cc080)
