### ISSUE TITLE
CPU and GPU Hybrid Mode: Hot Ollama with CPU and cold vLLM for GPU

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#460]
Use case: GPUs are expensive and don't need them 24/7 however TTFT needs to stay low for cold starts.

Example for Llama 3.3 70B:
* Ollama with CPU and max target requests of 2, minScale = 1, maxScale=1 llama-3.3-70b-cpu
* vLLM on H100 with max target requests of 1024, minScale=0, maxScale=10, model_name llama-3.3.70b-h100

Expectations:
* KubeAI should send all requests up till max target requests to Ollama running on CPU
* KubeAI should prefer routing all requests to vLLM with GPU once that's scaled up and able to handle the requests.

Potential solutions (will expand this):
* a new ModelRouter resource that can expose a single model name e.g. llama-3.3-70b
* Expand the usage of ResourceProfiles of a model

**Comment by samos123** [comment]
Cursor response...


## Option 1: New ModelRouter Resource

Creating a new ModelRouter resource could be an elegant solution:

```yaml
apiVersion: kubeai.dev/v1
kind: ModelRouter
metadata:
  name: llama-3-70b
spec:
  
  backends:
  - modelRef: 
      name: llama-3-70b-cpu
      namespace: default
    condition: "always"  # This one is always available
    priority: 5  # Lower number = higher priority 
  
  - modelRef:
      name: llama-3-70b-h100
      namespace: default
    condition: "available"  # Only used when scaled up
```

**How it works:**
- The ModelRouter exposes a single endpoint to clients
- Initially routes to CPU model until it reaches maxTargetRequests
- When GPU model scales up (condition: "available"), it becomes preferred due to higher priority
- Could support additional routing rules based on request properties

**Pros:**
- Clean separation of concerns
- Explicit routing logic
- Flexible and extensible

**Cons:**
- Requires implementing a new resource type
- More complex than other options

## Option 2: Enhanced LoadBalancing Strategy

We could extend the existing LoadBalancing system with a new strategy type:

```yaml
apiVersion: kubeai.dev/v1
kind: Model
metadata:
  name: llama-3-70b
spec:
  # Common model config...
  loadBalancing:
    strategy: TieredPriority
    tieredPriority:
      tiers:
      - name: cpu-tier
        resourceProfile: "cpu-only"
        minReplicas: 1
        maxReplicas: 1
        targetRequests: 2
        priority: 0  # Lower = higher priority when under load
      
      - name: gpu-tier
        resourceProfile: "nvidia-h100"
        minReplicas: 0
        maxReplicas: 10
        targetRequests: 1024
        priority: 10  # Higher priority when available
```

**How it works:**
- Single Model resource with multiple tiers
- Each tier specifies a different resource profile and scaling parameters
- Requests route to CPU initially, then GPUs take over when they scale up

**Pros:**
- Builds on existing architecture
- Simpler to implement than a new resource
- Unified model concept

**Cons:**
- Complicates the Model spec
- Less flexible than dedicated router

## Option 3: ModelGroup Resource

A ModelGroup could provide a logical grouping of related Model resources:

```yaml
apiVersion: kubeai.dev/v1
kind: ModelGroup
metadata:
  name: llama-3-70b-group
spec:
  # Endpoint name exposed to clients
  exposedModelName: "llama-3-70b"
  
  models:
  - name: llama-3-70b-cpu
    role: "base"  # Always running as baseline
    maxLoad: 2
  
  - name: llama-3-70b-h100 
    role: "accelerator"  # Used when available and needed
    maxLoad: 1024
    
  routingPolicy: "priorityWithFallback"  # Use accelerators first when available
```

**How it works:**
- Groups logically related model deployments
- Defines roles and routing policies
- Routes requests based on availability and load

**Pros:**
- Clear logical grouping
- Separates routing from model definitions
- Explicit roles

**Cons:**
- Another new resource type to implement

## Option 4: Model Variant Annotations

We could use annotations or labels on existing Model resources:

```yaml
# First Model resource
apiVersion: kubeai.dev/v1
kind: Model
metadata:
  name: llama-3-70b-cpu
  annotations:
    kubeai.dev/model-group: "llama-3-70b"
    kubeai.dev/variant-type: "baseline"
    kubeai.dev/variant-priority: "0"
    kubeai.dev/max-load: "2"
spec:
  # CPU model config...

# Second Model resource  
apiVersion: kubeai.dev/v1
kind: Model
metadata:
  name: llama-3-70b-h100
  annotations:
    kubeai.dev/model-group: "llama-3-70b"
    kubeai.dev/variant-type: "accelerator"
    kubeai.dev/variant-priority: "10" 
    kubeai.dev/max-load: "1024"
spec:
  # GPU model config...
```

**How it works:**
- Model resources are tagged with group membership and roles
- KubeAI router discovers related models via annotations
- Routes based on availability and annotated properties

**Pros:**
- Minimal changes to existing architecture
- No new resource types
- Easily discoverable relationships

**Cons:**
- Less structured than formal resource types
- Limited expressiveness for complex routing logic

## Recommendation

I recommend pursuing the **ModelRouter** approach (Option 1) for several reasons:

1. It provides the cleanest separation of concerns
2. It offers the most flexibility for future enhancements
3. The routing logic is explicit and centralized
4. It maintains backward compatibility with existing Model resources
5. It can support more complex routing rules in the future

The ModelRouter could later be extended to support:
- A/B testing between model versions
- Request-property based routing (e.g., based on context length)
- Cost-optimization strategies
- Failover policies
- Quality-of-service tiers
