### ISSUE TITLE
Could you please provide an example of Ollama Load from PVC with a PersistentVolume whose volumeType is local?

### ISSUE THREAD

**Issue by leoho0722** [substratusai/kubeai#479]
Hi! I so excited that see the latest version KubeAI that can load ollama model from PVC.

I has already seen the example of Website and actually tested them.

I applied the `StorageClass`, `PersistentVolumeClaim`, `PersistentVolume` to Kubernetes.

volumeType of PersistentVolume uses `local`, so `nodeAffinity` is set.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ollama-model-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-pvc
  namespace: default
spec:
  storageClassName: ollama-model-local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-model-pv
  namespace: default
spec:
  storageClassName: ollama-model-local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /usr/share/ollama/.ollama/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu-d830mt
                - ubuntu-ms-7d98
```

Then, I uses the Job that load model to PVC.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-load-model-to-pvc
spec:
  template:
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          env:
            - name: OLLAMA_MODELS
              value: /model
          command:
            - /bin/sh
            - -c
            - |
              /bin/ollama serve &
              echo "Waiting for Ollama server to start..."
              sleep 10

              # Pull the model and ensure it downloads successfully
              echo "Pulling model llama2:7b..."
              if ! /bin/ollama pull llama2:7b; then
                echo "Failed to pull model"
                exit 1
              fi

              # Verify the model files exist
              echo "Verifying model files..."
              ls -R /model
              if [ ! -d "/model/blobs" ] || [ ! -d "/model/manifests" ]; then
                echo "Model directories not found"
                exit 1
              fi

              echo "Model setup completed successfully"
              ls -la /model/manifests/registry.ollama.ai/library/llama2/7b
          volumeMounts:
            - name: ollama-model-local-storage
              mountPath: /model
      volumes:
        - name: ollama-model-local-storage
          persistentVolumeClaim:
            claimName: ollama-model-pvc
            readOnly: false
      restartPolicy: OnFailure
```

Finally, deployed the `llama2-7b` model that load from PVC.

```yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama2-7b
  namespace: default
spec:
  features: [TextGeneration]
  url: pvc://ollama-model-pvc?model=llama2:7b
  engine: OLlama
  replicas: 1
  minReplicas: 1
  targetRequests: 50
  scaleDownDelaySeconds: 30
  loadBalancing:
    strategy: "PrefixHash"
  env:
    OLLAMA_KEEP_ALIVE: "0s"
  resourceProfile: cpu:4
```

But I follow the above steps, got the below error

```
Startup probe failed: Error: mkdir /model/manifests/registry.ollama.ai/library/llama2-7b: permission denied
```

![Image](https://github.com/user-attachments/assets/8160285e-5fce-432b-98ee-698d2de20225)

Kubernetes version: 1.31.3
KubeAI version: 0.18.0
